using BlazorWebApp.Models;

namespace BlazorWebApp.Scheduler.Models
{
    /// <summary>
    /// Immutable snapshot of a single execution of a <see cref="Job"/>.
    /// Captured at trigger time: <see cref="BaseParameters"/> and <see cref="Actions"/> are
    /// cloned from the owning job so subsequent edits to the job definition do not alter the
    /// historical record. Runtime progress fields (<see cref="CompletedImages"/> etc.) are
    /// updated as the run executes and then finalized on completion / cancellation / failure.
    /// </summary>
    public sealed class Run
    {
        /// <summary>Unique identifier for the run.</summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>Owning job id.</summary>
        public Guid JobId { get; set; }

        /// <summary>
        /// Monotonic per-job run number. Assigned from <see cref="Job.RunCounter"/> at creation
        /// and never reused even when older runs are deleted.
        /// </summary>
        public int RunNumber { get; set; }

        /// <summary>Display label, typically "&lt;Job Name&gt; - Run #N".</summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>Timestamp the run was triggered.</summary>
        public DateTime StartedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Timestamp the run reached a terminal status (Completed / Failed / Cancelled).</summary>
        public DateTime? CompletedAt { get; set; }

        /// <summary>Timestamp of the last progress update.</summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>Current lifecycle status of this run.</summary>
        public JobStatus Status { get; set; } = JobStatus.Running;

        /// <summary>Workflow id used for this run, snapshotted from the job at trigger time.</summary>
        public Guid? WorkflowId { get; set; }

        /// <summary>Snapshot of <see cref="Job.BaseParameters"/> at trigger time.</summary>
        public GenerationParameters BaseParameters { get; set; } = new();

        /// <summary>Snapshot of the ordered <see cref="Job.Actions"/> at trigger time.</summary>
        public List<JobAction> Actions { get; set; } = new();

        /// <summary>
        /// Snapshot of <see cref="Job.OutputConfig"/> at trigger time. Holds the default
        /// project/folder routing used for every iteration of this run unless a per-action
        /// <see cref="JobAction.OutputOverride"/> overrides it.
        /// </summary>
        public JobOutputConfig OutputConfig { get; set; } = new();

        /// <summary>Total iterations planned for this run.</summary>
        public int TotalIterations { get; set; }

        /// <summary>Count of images successfully generated.</summary>
        public int CompletedImages { get; set; }

        /// <summary>Count of failed generations.</summary>
        public int FailedImages { get; set; }

        /// <summary>Zero-based index of the action currently executing (or next to execute).</summary>
        public int CurrentActionIndex { get; set; }

        /// <summary>Zero-based iteration index within the current action.</summary>
        public int CurrentIterationIndex { get; set; }

        /// <summary>IDs of images generated by this run across all iterations.</summary>
        public List<int> GeneratedImageIds { get; set; } = new();

        /// <summary>Optional error message when the run ended in <see cref="JobStatus.Failed"/>.</summary>
        public string? Error { get; set; }
    }
}
